In [21]:
my_list = [1, 2, 3, 4, 5]
type(my_list)

list

## Using Array Module

In [48]:
from array import array

# The first argument specifies the type of elements in the array (e.g., 'i' for integers)
# The second argument is a list of values to initialize the array

my_array = array('i', [1, 2, 3, 4, 5])

In [49]:
my_array

array('i', [1, 2, 3, 4, 5])

In [50]:
my_array[0]

1

In [51]:
my_array[0] = 6

In [52]:
my_array

array('i', [6, 2, 3, 4, 5])

In [53]:
my_array.insert(0,1)

In [54]:
my_array

array('i', [1, 6, 2, 3, 4, 5])

In [55]:
my_array.pop(0)   #where 0 is index

1

In [56]:
my_array

array('i', [6, 2, 3, 4, 5])

## Using Numpy Module

In [59]:
import numpy as np

my_array = np.array([1, 2, 3, 4, 5])

In [60]:
my_array

array([1, 2, 3, 4, 5])

In [61]:
my_array = np.insert(my_array,0,10)

In [62]:
my_array

array([10,  1,  2,  3,  4,  5])

In [65]:
new_array = np.delete(my_array, 0)

In [66]:
new_array

array([1, 2, 3, 4, 5])

## Array of Characters

In [39]:
char_array = array('u',["a", "b", "c"])

In [40]:
char_array

array('u', 'abc')

&therefore; Array of characters will be converted into string

## Numpy array differences 

In [44]:
fruit = ["Apple","Orange",1]

In [45]:
fruit_array = np.array(fruit)

In [46]:
fruit_array

array(['Apple', 'Orange', '1'], dtype='<U11')

Note: Data type is changed